### ISSUE TITLE
时间处理出错

### ISSUE THREAD

**Issue by wwqgtxx** [ZeroMean/leave-school#1]
https://github.com/ZeroMean/leave-school/blob/98c5f4eaf7ff0322c97b060abc176a40a9013dad/pages/QRCode/QRCode.vue#L131
https://github.com/ZeroMean/leave-school/blob/98c5f4eaf7ff0322c97b060abc176a40a9013dad/pages/viewLeaves/viewLeaves.vue#L226
https://github.com/ZeroMean/leave-school/blob/98c5f4eaf7ff0322c97b060abc176a40a9013dad/pages/QRCode/QRCode.vue#L155

这里的
```javascript
Number(date.getMonth() + 1).toString()
```
应该为

```javascript
Number(date.getMonth() + 1).toString().length
```

**Comment by ZeroMean** [comment]
感谢大佬,已修复。
